#!/usr/bin/env bash

declare -g AB_USERNAME="aurbuilder"
declare -g AB_HOME_DIR="/var/lib/aurbuilder"
declare -g AB_USER_SHELL="/usr/bin/nologin"
declare -g AB_SUDOERS_FILE="/etc/sudoers.d/${AB_USERNAME}"

check_dependencies() {
    local deps=(openssl git)
    for dep in "${deps[@]}"; do
        if [ ! "$(command -v "$dep")" ]; then
            echo "Dependency not found: ${dep}"
            echo "Installing..."
            pacman -S --needed --noconfirm "$dep"
        fi
    done
}

install() {
    check_dependencies
    local root_dir=$1
    local password=$(openssl rand -base64 12)
    [ "$(id -u "aurbuilder")" ] && return
    useradd --system --no-user-group --no-create-home --home-dir "$AB_HOME_DIR" --shell "$AB_USER_SHELL" "$AB_USERNAME"
    mkdir --parents "$AB_HOME_DIR"
    chmod 777 "$AB_HOME_DIR"
    if [ -n "$root_dir" ]; then
        chpasswd --root "$root_dir" <<<"${AB_USERNAME}:${password}"
    else
        chpasswd <<<"${AB_USERNAME}:${password}"
    fi
    if [ ! -f "$AB_SUDOERS_FILE" ]; then
        echo "${AB_USERNAME} ALL=(ALL:ALL) NOPASSWD: ALL" >"$AB_SUDOERS_FILE"
        echo "root ALL=(${AB_USERNAME}) NOPASSWD: ALL" >>"$AB_SUDOERS_FILE"
    fi
}

build_package() {
    local package=$1
    local url="https://aur.archlinux.org/${package}.git"
    git clone "$url" --depth 1
    cd "$package" || exit $?
    makepkg -sirc --noconfirm --needed
    cd ..
    rm -rf "$package"
}

run() {
    local packages=("$@")
    local initial_dir=$(pwd)
    if ! cd "$AB_HOME_DIR"; then
        mkdir --parents "$AB_HOME_DIR"
        chmod 777 "$AB_HOME_DIR"
        cd "$AB_HOME_DIR" || exit $?
    fi
    for pkg in "${packages[@]}"; do
        sudo -u "$AB_USERNAME" build_package "$pkg"
    done
    cd "$initial_dir" || exit $?
}
