[window]
dimensions = { columns = 120, lines = 24 }
padding = { x = 8, y = 8 }
opacity = 0.9

[font]
size = 10
offset = { x = 1, y = 4 }
normal = { family = "JetBrainsMono Nerd Font" }

[cursor]
style = { blinking = "On" }

[mouse]
hide_when_typing = true

[general]
import = [
	"~/.config/alacritty/color-scheme.toml",
	"~/.config/alacritty/bindings.toml"
]

[terminal]
shell = "/usr/bin/fish"
