name: Build release URL

on:
  push:
    branches: [main]
    paths: [archzen.sh]

  workflow_dispatch:

env:
  MAIN_FILE: archzen.sh
  SOURCE_PATH: index.html
  OUTPUT_PATH: .
  STORAGE_BRANCH: storage

jobs:
  setup:
    name: Setup environment
    runs-on: ubuntu-latest

    outputs:
      profile_name: ${{ steps.api.outputs.profile_name }}
      profile_url: ${{ steps.api.outputs.profile_url }}
      project_url: ${{ steps.project.outputs.project_url }}
      project_raw_url: ${{ steps.project.outputs.project_raw_url }}
      license_name: ${{ steps.api.outputs.license_name }}
      license_url: ${{ steps.api.outputs.license_url }}
      timestamp: ${{ steps.api.outputs.timestamp }}

    steps:
      - name: Install jq if not present
        run: |
          if ! command -v jq &> /dev/null; then
            echo "jq not found, installing..."
            sudo apt-get update && sudo apt-get install -y jq
          else
            echo "jq is already installed"
          fi

      - name: Fetch data from GitHub API
        id: api
        run: |
          fetch_git_api() {
            local endpoint=$1
            local response
            response="$(
              curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com${endpoint}"
            )"
            echo "$response"
          }

          echo "Fetching license data... Endpoint: '/repos/${GITHUB_REPOSITORY}/license'"
          RESPONSE="$(fetch_git_api "/repos/${GITHUB_REPOSITORY}/license")"
          LICENSE="$(echo "$RESPONSE" | jq -r .license.spdx_id)"
          LICENSE_URL="$(echo "$RESPONSE" | jq -r .html_url)"

          echo "Fetching profile data... Endpoint: '/users/${GITHUB_REPOSITORY_OWNER}')"
          RESPONSE="$(fetch_git_api "/users/${GITHUB_REPOSITORY_OWNER}")"
          PROFILE_NAME="$(echo "$RESPONSE" | jq -r .name)"
          PROFILE_URL="$(echo "$RESPONSE" | jq -r .html_url)"

          echo "PROFILE_NAME: ${PROFILE_NAME}"
          echo "PROFILE_URL: ${PROFILE_URL}"
          echo "LICENSE_NAME: ${LICENSE_NAME}"
          echo "LICENSE_URL: ${LICENSE_URL}"

          echo "profile_name=${PROFILE_NAME}" >> $GITHUB_OUTPUT
          echo "profile_url=${PROFILE_URL}" >> $GITHUB_OUTPUT
          echo "license_name=${LICENSE_NAME}" >> $GITHUB_OUTPUT
          echo "license_url=${LICENSE_URL}" >> $GITHUB_OUTPUT

      - name: Fetch project data
        id: project
        run: |
          PROJECT_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
          PROJECT_RAW_URL="raw.githubusercontent.com/${GITHUB_REPOSITORY}/main"
          TIMESTAMP=$(date +"%Y.%m.%d-%H%M%S")

          echo "PROJECT_URL: ${PROJECT_URL}"
          echo "PROJECT_RAW_URL: ${PROJECT_RAW_URL}"
          echo "TIMESTAMP: ${TIMESTAMP}"
          
          echo "project_url=${PROJECT_URL}" >> $GITHUB_OUTPUT
          echo "project_raw_url=${PROJECT_RAW_URL}" >> $GITHUB_OUTPUT
          echo "timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT

  build:
    name: Build script
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download file
        run: |
          PROJECT_RAW_URL="${{ needs.setup.outputs.project_raw_url }}"
          echo "PROJECT_RAW_URL: ${PROJECT_RAW_URL}"
          curl -Lo $SOURCE_PATH "${PROJECT_RAW_URL}/main/${MAIN_FILE}"

      - name: Update file parameters
        run: |
          profile_name="${{ needs.setup.outputs.profile_name }}"
          profile_url="${{ needs.setup.outputs.profile_url }}"
          project_url="${{ needs.setup.outputs.project_url }}"
          project_raw_url="${{ needs.setup.outputs.project_raw_url }}"
          license_name="${{ needs.setup.outputs.license_name }}"
          license_url="${{ needs.setup.outputs.license_url }}"

          echo "profile_name: ${profile_name}"
          echo "profile_url: ${profile_url}"
          echo "project_url: ${project_url}"
          echo "project_raw_url: ${project_url}"
          echo "license_name: ${license_name}"
          echo "license_url: ${license_url}"

          sed -i "s|{{PROJECT_AUTHOR}}|${profile_name} (${profile_url})|" $SOURCE_PATH
          sed -i "s|{{PROJECT_URL}}|${project_url}|" $SOURCE_PATH
          sed -i "s|{{PROJECT_RAW_URL}}|${project_raw_url}|" $SOURCE_PATH
          sed -i "s|{{LICENSE_NAME}}|${license_name}|" $SOURCE_PATH
          sed -i "s|{{LICENSE_URL}}|${license_url}|" $SOURCE_PATH

      - name: Save to storage branch
        uses: StirlingLabs/BranchStorageAction@v22.03.0
        with:
          src: ${{ env.SOURCE_PATH }}
          dst: ${{ env.OUTPUT_PATH }}
          storage-branch: ${{ env.STORAGE_BRANCH }}
          prune: true
          comment: Release ${{ needs.setup.outputs.timestamp }}

